name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/teyvat-archive-server
            git pull origin master
            cat > .env <<EOT
            PROJECT_AMBR_BASE_URL=${{ secrets.PROJECT_AMBR_BASE_URL }}
            HOYOPLAY_REQUEST_CAPTURE_URL=${{ secrets.HOYOPLAY_REQUEST_CAPTURE_URL }}
            HOYO_GAME_CAPTURE_URL=${{ secrets.HOYO_GAME_CAPTURE_URL }}
            HOYO_API=${{ secrets.HOYO_API }}
            AUTH_TOKEN=${{ secrets.AUTH_TOKEN }}
            AZA_GG_API=${{ secrets.AZA_GG_API }}
            PORT=${{ secrets.PORT }}
            EOT
            docker-compose down
            docker-compose up -d --build
          EOF
          echo "Deployment completed successfully."
      - name: Notify deployment status
        run: |
          if [ $? -eq 0 ]; then
            echo "Deployment succeeded."
          else
            echo "Deployment failed."
            exit 1
          fi
