name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # We need the previous commit to compare versions

      - name: Check if version changed
        id: version_check
        run: |
          # Get current version
          CURRENT_VERSION=$(node -p "require('./package.json').version")

          # Get previous version
          git checkout HEAD~1
          PREVIOUS_VERSION=$(node -p "require('./package.json').version" 2>/dev/null || echo "0.0.0")
          git checkout -  # Go back to current commit

          if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
            echo "Version changed from $PREVIOUS_VERSION to $CURRENT_VERSION"
            echo "should_deploy=true" >> $GITHUB_OUTPUT
          else
            echo "Version unchanged: $CURRENT_VERSION"
            echo "should_deploy=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up SSH
        if: steps.version_check.outputs.should_deploy == 'true'
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        if: steps.version_check.outputs.should_deploy == 'true'
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/teyvat-archive-server
            git pull origin master
            mkdir -p src/data/enka-cache
          EOF

      - name: Updating ENV
        if: steps.version_check.outputs.should_deploy == 'true'
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/teyvat-archive-server
            cat > .env << 'INNER_EOF'
          PROJECT_AMBR_BASE_URL=${{ secrets.PROJECT_AMBR_BASE_URL }}
          HOYOPLAY_REQUEST_CAPTURE_URL=${{ secrets.HOYOPLAY_REQUEST_CAPTURE_URL }}
          HOYO_GAME_CAPTURE_URL=${{ secrets.HOYO_GAME_CAPTURE_URL }}
          AUTH_TOKEN=${{ secrets.AUTH_TOKEN }}
          HOYO_API=${{ secrets.HOYO_API }}
          AZA_GG_API=${{ secrets.AZA_GG_API }}
          HAKUSH_ABYSS_API=${{ secrets.HAKUSH_ABYSS_API }}
          PORT=${{ secrets.PORT }}
          SUPABASE_URL=${{ secrets.SUPABASE_URL }}
          SUPABASE_CONNECTION_STRING=${{ secrets.SUPABASE_CONNECTION_STRING }}
          SUPABASE_SERVICE_ROLE=${{ secrets.SUPABASE_SERVICE_ROLE}}
          NODE_ENV=production
          INNER_EOF
            echo "Updated .env file with secrets."
          EOF

      - name: Building Docker
        if: steps.version_check.outputs.should_deploy == 'true'
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/teyvat-archive-server
            docker-compose down
            docker-compose up -d --build
            docker system prune -f
          EOF

      - name: Deployment Success
        if: steps.version_check.outputs.should_deploy == 'true'
        run: echo "Deployment to EC2 successful!"

      - name: Clean up
        if: steps.version_check.outputs.should_deploy == 'true'
        run: |
          rm -rf ~/.ssh/id_ed25519
          rm -rf ~/.ssh/known_hosts
          echo "Cleaned up SSH keys."
